language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./tests